blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/wzh4464/auto-expense-tracker/discussions
    about: Ask questions or start discussions about the project
